### ISSUE TITLE
Distributed Laravel Zero App

### ISSUE THREAD

**Issue by ekandreas** [nunomaduro/laravel-console-dusk#10]
How to handle storage write with a Laravel Zero Phar App?
```
mkdir(): phar error: cannot create directory "phar:///.../builds/zero-test/storage/.", write operations disabled
```

**Comment by manelgavalda** [comment]
Hey, I got the same problem while trying to use the `app:build` command. I solved it by modifying my php cli config file (`php.ini`):

By default this line is commented:
```
;phar.readonly = On
```
You should uncomment it and turn it off:
```
phar.readonly = Off
```
Then just restart your php service and build it again.

Hope this helps.
