### ISSUE TITLE
Multiple browsers

### ISSUE THREAD

**Issue by shadoWalker89** [nunomaduro/laravel-console-dusk#19]
Hi,

Laravel dusk allows to create more then one browser like this

```php
$this->browse(function ($first, $second) {
    $first->loginAs(User::find(1))
          ->visit('/home')
          ->waitForText('Message');

    $second->loginAs(User::find(2))
           ->visit('/home')
           ->waitForText('Message')
           ->type('message', 'Hey Taylor')
           ->press('Send');

    $first->waitForText('Hey Taylor')
          ->assertSee('Jeffrey Way');
});
```

This is not possible in laravel zero due to always passing one browser in 
https://github.com/nunomaduro/laravel-console-dusk/blob/9ae9a9a47944f8490b7a6d6a25e0d01405fd8545/src/Manager.php#L30-L35

**Comment by manelgavalda** [comment]
Hey,
Just created a PR for this. 
@owenvoke @nunomaduro I would appreciate if you can take a look at the it.
Thanks!
