### ISSUE TITLE
FEATURE: Allow customizing the chrome driver options globally

### ISSUE THREAD

**Issue by lhilton** [nunomaduro/laravel-console-dusk#26]
I need to be able to pass some additional flags to the chrome driver (for example, `--ignore-certificate-errors`). I would like to be able to do this via the config file.

Incoming PR proposing a solution as well.

**Comment by ivanzhang** [comment]
and allow env('DUSK_DRIVER_URL') instead of hardcode 'http://localhost:9515'

**Comment by underdpt** [comment]
Hello,

I'm sorry PR #27 seems stalled, so I've continued the work on PR #29, I hope that's ok for the original developer.
