### ISSUE TITLE
How to make it work with laravel-zero

### ISSUE THREAD

**Issue by quarkmarino** [nunomaduro/laravel-console-dusk#3]
Hey Nuno, I'm having troubles using this package with laravel-zero, I missed the live talk but im following the record, how should I enable it to use with a command, I required it with composer and is installed correctly but when I run a Command that calls the 
```php
$this->browse();
```
from within the handle method, I get a
```
Method App\Commands\Convert::browse does not exist.
```
error.

Should I install it in some special way?, or enable it via SerivceProvider? and how?

Thank you.

**Comment by nunomaduro** [comment]
@quarkmarino Please perform a `composer update laravel-zero/framework`.

Then type: `php <your-app-name> app:install console-dusk`. And all should be good 🙂

**Comment by quarkmarino** [comment]
Running commands... Ok, now I need to install php-curl... All good at the end, I'm now visiting stuff -Yay. Thank you very much, that worked fine.

**Comment by nunomaduro** [comment]
Perfect! Enjoy! 🎉
