### ISSUE TITLE
Fails to connect to process since Chrome webdriver version 128

### ISSUE THREAD

**Issue by nsrosenqvist** [nunomaduro/laravel-console-dusk#40]
Since version 128 the web driver starts at port 0, selecting an available port automatically instead. Therefore, laravel-console-dusk fails to connect to the server since it assumes it will be running on port 9515.

<img width="1492" alt="Screenshot 2024-10-25 at 13 59 01" src="https://github.com/user-attachments/assets/9a69080f-d31d-4884-a498-dc44afc28ed7">

**Comment by nsrosenqvist** [comment]
Was about to submit a PR when I noticed that it was fixed in master way back in April. @nunomaduro would you please consider tagging a new release?

**Comment by owenvoke** [comment]
Apologies, this was fixed by https://github.com/nunomaduro/laravel-console-dusk/pull/38, but I never created a release. 😐 Just released [`v1.13.1`](https://github.com/nunomaduro/laravel-console-dusk/releases/tag/v1.13.1) with the fix.

**Comment by nsrosenqvist** [comment]
@owenvoke thanks! 🙏
