### ISSUE TITLE
[1.1] Missing configuration file

### ISSUE THREAD

**Issue by nerdalertdk** [nunomaduro/laravel-console-dusk#6]
Hi

Is there anyway to mute the output ?
on complex request there is a lot of noise.

would like just to use $this-info() when i need something echo to the screen 

Edit: found inSecret(), that helps a little bout an global option would be nice :)

**Comment by nunomaduro** [comment]
@nerdalertdk That would be a good first issue. Publish a configuration file that allows to configure those options.

**Comment by nunomaduro** [comment]
Thanks to @claudiunicolaa this feature has been added.
