### ISSUE TITLE
Class 'NunoMaduro\LaravelConsoleDusk\ConsoleBrowser' not found

### ISSUE THREAD

**Issue by webparadoxer** [nunomaduro/laravel-console-dusk#7]
`<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class jstest extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'jstest';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->browse(function ($browser) {
            $browser->visit('http://laravel-zero.com')
                ->assertSee('Collision');
        });

    }
}`
fresh install laravel:
php artisan --version
Laravel Framework 5.6.34

**Comment by nunomaduro** [comment]
Thanks for reporting that issue.

The version v1.0.5 has already that fix.
